name: KDDockWidgets
description: Dockwidget library for flutter

environment:
  sdk: ">=3.5.0"

dependencies:
  ffi: ^2.1.3
  intl:
  meta:
  flutter:
    sdk: flutter
  signals_slots: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
  ffigen: ^16.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/classic_indicators/

ffigen:
  output: "lib/private/kddw_bindings.dart"
  llvm-path:
    - "/data/installation/clang-trunk/lib/libclang.so"
  headers:
    entry-points:
      - "../kddw_bindings.h"
  preamble: |
    // This file is part of KDDockWidgets.
    // SPDX-FileCopyrightText: 2024 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
    // SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only
    // Contact KDAB at <info@kdab.com> for commercial licensing options.
